# Generated by Django 5.1.2 on 2024-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_project_projectimage_projectvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
