# Generated by Django 5.1.2 on 2024-11-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_projectimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.projectimage'),
        ),
    ]
