# Generated by Django 5.1.2 on 2024-11-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projectvideo_iframe_url_alter_projectvideo_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='iframe_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Iframe URL'),
        ),
    ]
